// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace BossRoom
{

public enum ClassType : sbyte
{
  None = 0,
  Tank = 1,
  Archer = 2,
  Mage = 3,
  Rogue = 4,
};


}
