// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace PacketDefine
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public enum PACKET_ID : byte
{
  NONE = 0,
  PACKET_LOGIN_REQ = 1,
  PACKET_LOGIN_RES = 2,
  PACKET_CREATE_LOBBY_REQ = 3,
  PACKET_CREATE_LOBBY_RES = 4,
  PACKET_ENTER_LOBBY_REQ = 5,
  PACKET_ENTER_LOBBY_RES = 6,
  PACKET_LEAVE_LOBBY_REQ = 7,
  PACKET_LEAVE_LOBBY_RES = 8,
};

public enum ErrorCode : short
{
  SUCCESS = 0,
  USER_MGR_INVALID_USER_INDEX = 11,
  USER_MGR_INVALID_USER_UNIQUEID = 12,
  LOGIN_USER_AUTHURIZE_FAIL = 1001,
  LOGIN_USER_ALREADY = 1002,
  LOGIN_USER_USED_ALL_OBJ = 1003,
  NEW_ROOM_USED_ALL_OBJ = 2001,
  NEW_ROOM_FAIL_ENTER = 2002,
  ENTER_ROOM_NOT_FIND_USER = 2003,
  ENTER_ROOM_INVALID_USER_STATUS = 2004,
  ENTER_ROOM_NOT_USED_STATUS = 2005,
  ENTER_ROOM_FULL_USER = 2006,
  ROOM_INVALID_INDEX = 2007,
  ROOM_NOT_USED = 2008,
  ROOM_TOO_MANY_PACKET = 2009,
  LEAVE_ROOM_INVALID_ROOM_INDEX = 2010,
  CHAT_ROOM_INVALID_ROOM_INDEX = 2011,
};

public enum PacketOldID : short
{
  INVALID = 0,
  SYSTEM_CLIENT_CONNECT = 11,
  SYSTEM_CLIENT_DISCONNECTD = 12,
  LoginReq = 201,
  LoginRes = 202,
  NewLobbyReq = 203,
  NewLobbyRes = 204,
  EnterLobbyReq = 206,
  EnterLobbyRes = 207,
  LeaveLobbyReq = 209,
  LeaveLobbyRes = 210,
  ChatLobbyReq = 214,
  ChatLobbyRes = 215,
  ChatLobbyNtf = 216,
  GameStartReqPkt = 301,
  GameStartResPkt = 302,
  GameStartNtfPkt = 303,
  GameSyncReqPkt = 304,
  GameSyncNtfPkt = 305,
  GameScoreUpdateReqPkt = 306,
  GameScoreUpdateNtfPkt = 307,
  GameScoreUpdateResPkt = 308,
  GameEndReqPkt = 311,
  GameEndResPkt = 312,
  GameEndNtfPkt = 313,
};

public struct Packet : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_3_3(); }
  public static Packet GetRootAsPacket(ByteBuffer _bb) { return GetRootAsPacket(_bb, new Packet()); }
  public static Packet GetRootAsPacket(ByteBuffer _bb, Packet obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Packet __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public PacketDefine.PACKET_ID PacketIdType { get { int o = __p.__offset(4); return o != 0 ? (PacketDefine.PACKET_ID)__p.bb.Get(o + __p.bb_pos) : PacketDefine.PACKET_ID.NONE; } }
  public TTable? PacketId<TTable>() where TTable : struct, IFlatbufferObject { int o = __p.__offset(6); return o != 0 ? (TTable?)__p.__union<TTable>(o + __p.bb_pos) : null; }
  public PacketDefine.PACKET_LOGIN_REQ PacketIdAsPACKET_LOGIN_REQ() { return PacketId<PacketDefine.PACKET_LOGIN_REQ>().Value; }
  public PacketDefine.PACKET_LOGIN_RES PacketIdAsPACKET_LOGIN_RES() { return PacketId<PacketDefine.PACKET_LOGIN_RES>().Value; }
  public PacketDefine.PACKET_CREATE_LOBBY_REQ PacketIdAsPACKET_CREATE_LOBBY_REQ() { return PacketId<PacketDefine.PACKET_CREATE_LOBBY_REQ>().Value; }
  public PacketDefine.PACKET_CREATE_LOBBY_RES PacketIdAsPACKET_CREATE_LOBBY_RES() { return PacketId<PacketDefine.PACKET_CREATE_LOBBY_RES>().Value; }
  public PacketDefine.PACKET_ENTER_LOBBY_REQ PacketIdAsPACKET_ENTER_LOBBY_REQ() { return PacketId<PacketDefine.PACKET_ENTER_LOBBY_REQ>().Value; }
  public PacketDefine.PACKET_ENTER_LOBBY_RES PacketIdAsPACKET_ENTER_LOBBY_RES() { return PacketId<PacketDefine.PACKET_ENTER_LOBBY_RES>().Value; }
  public PacketDefine.PACKET_LEAVE_LOBBY_REQ PacketIdAsPACKET_LEAVE_LOBBY_REQ() { return PacketId<PacketDefine.PACKET_LEAVE_LOBBY_REQ>().Value; }
  public PacketDefine.PACKET_LEAVE_LOBBY_RES PacketIdAsPACKET_LEAVE_LOBBY_RES() { return PacketId<PacketDefine.PACKET_LEAVE_LOBBY_RES>().Value; }

  public static Offset<PacketDefine.Packet> CreatePacket(FlatBufferBuilder builder,
      PacketDefine.PACKET_ID packet_id_type = PacketDefine.PACKET_ID.NONE,
      int packet_idOffset = 0) {
    builder.StartTable(2);
    Packet.AddPacketId(builder, packet_idOffset);
    Packet.AddPacketIdType(builder, packet_id_type);
    return Packet.EndPacket(builder);
  }

  public static void StartPacket(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddPacketIdType(FlatBufferBuilder builder, PacketDefine.PACKET_ID packetIdType) { builder.AddByte(0, (byte)packetIdType, 0); }
  public static void AddPacketId(FlatBufferBuilder builder, int packetIdOffset) { builder.AddOffset(1, packetIdOffset, 0); }
  public static Offset<PacketDefine.Packet> EndPacket(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<PacketDefine.Packet>(o);
  }
  public static void FinishPacketBuffer(FlatBufferBuilder builder, Offset<PacketDefine.Packet> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedPacketBuffer(FlatBufferBuilder builder, Offset<PacketDefine.Packet> offset) { builder.FinishSizePrefixed(offset.Value); }
}

public struct PACKET_LOGIN_REQ : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_3_3(); }
  public static PACKET_LOGIN_REQ GetRootAsPACKET_LOGIN_REQ(ByteBuffer _bb) { return GetRootAsPACKET_LOGIN_REQ(_bb, new PACKET_LOGIN_REQ()); }
  public static PACKET_LOGIN_REQ GetRootAsPACKET_LOGIN_REQ(ByteBuffer _bb, PACKET_LOGIN_REQ obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public PACKET_LOGIN_REQ __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string UsedId { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetUsedIdBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetUsedIdBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetUsedIdArray() { return __p.__vector_as_array<byte>(4); }
  public string Password { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetPasswordBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetPasswordBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetPasswordArray() { return __p.__vector_as_array<byte>(6); }

  public static Offset<PacketDefine.PACKET_LOGIN_REQ> CreatePACKET_LOGIN_REQ(FlatBufferBuilder builder,
      StringOffset used_idOffset = default(StringOffset),
      StringOffset passwordOffset = default(StringOffset)) {
    builder.StartTable(2);
    PACKET_LOGIN_REQ.AddPassword(builder, passwordOffset);
    PACKET_LOGIN_REQ.AddUsedId(builder, used_idOffset);
    return PACKET_LOGIN_REQ.EndPACKET_LOGIN_REQ(builder);
  }

  public static void StartPACKET_LOGIN_REQ(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddUsedId(FlatBufferBuilder builder, StringOffset usedIdOffset) { builder.AddOffset(0, usedIdOffset.Value, 0); }
  public static void AddPassword(FlatBufferBuilder builder, StringOffset passwordOffset) { builder.AddOffset(1, passwordOffset.Value, 0); }
  public static Offset<PacketDefine.PACKET_LOGIN_REQ> EndPACKET_LOGIN_REQ(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<PacketDefine.PACKET_LOGIN_REQ>(o);
  }
}

public struct PACKET_LOGIN_RES : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_3_3(); }
  public static PACKET_LOGIN_RES GetRootAsPACKET_LOGIN_RES(ByteBuffer _bb) { return GetRootAsPACKET_LOGIN_RES(_bb, new PACKET_LOGIN_RES()); }
  public static PACKET_LOGIN_RES GetRootAsPACKET_LOGIN_RES(ByteBuffer _bb, PACKET_LOGIN_RES obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public PACKET_LOGIN_RES __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public PacketDefine.ErrorCode ErrorCode { get { int o = __p.__offset(4); return o != 0 ? (PacketDefine.ErrorCode)__p.bb.GetShort(o + __p.bb_pos) : PacketDefine.ErrorCode.SUCCESS; } }
  public string UsedId { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetUsedIdBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetUsedIdBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetUsedIdArray() { return __p.__vector_as_array<byte>(6); }

  public static Offset<PacketDefine.PACKET_LOGIN_RES> CreatePACKET_LOGIN_RES(FlatBufferBuilder builder,
      PacketDefine.ErrorCode error_code = PacketDefine.ErrorCode.SUCCESS,
      StringOffset used_idOffset = default(StringOffset)) {
    builder.StartTable(2);
    PACKET_LOGIN_RES.AddUsedId(builder, used_idOffset);
    PACKET_LOGIN_RES.AddErrorCode(builder, error_code);
    return PACKET_LOGIN_RES.EndPACKET_LOGIN_RES(builder);
  }

  public static void StartPACKET_LOGIN_RES(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddErrorCode(FlatBufferBuilder builder, PacketDefine.ErrorCode errorCode) { builder.AddShort(0, (short)errorCode, 0); }
  public static void AddUsedId(FlatBufferBuilder builder, StringOffset usedIdOffset) { builder.AddOffset(1, usedIdOffset.Value, 0); }
  public static Offset<PacketDefine.PACKET_LOGIN_RES> EndPACKET_LOGIN_RES(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<PacketDefine.PACKET_LOGIN_RES>(o);
  }
}

public struct PACKET_CREATE_LOBBY_REQ : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_3_3(); }
  public static PACKET_CREATE_LOBBY_REQ GetRootAsPACKET_CREATE_LOBBY_REQ(ByteBuffer _bb) { return GetRootAsPACKET_CREATE_LOBBY_REQ(_bb, new PACKET_CREATE_LOBBY_REQ()); }
  public static PACKET_CREATE_LOBBY_REQ GetRootAsPACKET_CREATE_LOBBY_REQ(ByteBuffer _bb, PACKET_CREATE_LOBBY_REQ obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public PACKET_CREATE_LOBBY_REQ __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void StartPACKET_CREATE_LOBBY_REQ(FlatBufferBuilder builder) { builder.StartTable(0); }
  public static Offset<PacketDefine.PACKET_CREATE_LOBBY_REQ> EndPACKET_CREATE_LOBBY_REQ(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<PacketDefine.PACKET_CREATE_LOBBY_REQ>(o);
  }
}

public struct PACKET_CREATE_LOBBY_RES : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_3_3(); }
  public static PACKET_CREATE_LOBBY_RES GetRootAsPACKET_CREATE_LOBBY_RES(ByteBuffer _bb) { return GetRootAsPACKET_CREATE_LOBBY_RES(_bb, new PACKET_CREATE_LOBBY_RES()); }
  public static PACKET_CREATE_LOBBY_RES GetRootAsPACKET_CREATE_LOBBY_RES(ByteBuffer _bb, PACKET_CREATE_LOBBY_RES obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public PACKET_CREATE_LOBBY_RES __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public PacketDefine.ErrorCode ErrorCode { get { int o = __p.__offset(4); return o != 0 ? (PacketDefine.ErrorCode)__p.bb.GetShort(o + __p.bb_pos) : PacketDefine.ErrorCode.SUCCESS; } }
  public short RoomId { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetShort(o + __p.bb_pos) : (short)0; } }
  public string EnterKey { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetEnterKeyBytes() { return __p.__vector_as_span<byte>(8, 1); }
#else
  public ArraySegment<byte>? GetEnterKeyBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public byte[] GetEnterKeyArray() { return __p.__vector_as_array<byte>(8); }

  public static Offset<PacketDefine.PACKET_CREATE_LOBBY_RES> CreatePACKET_CREATE_LOBBY_RES(FlatBufferBuilder builder,
      PacketDefine.ErrorCode error_code = PacketDefine.ErrorCode.SUCCESS,
      short room_id = 0,
      StringOffset enter_keyOffset = default(StringOffset)) {
    builder.StartTable(3);
    PACKET_CREATE_LOBBY_RES.AddEnterKey(builder, enter_keyOffset);
    PACKET_CREATE_LOBBY_RES.AddRoomId(builder, room_id);
    PACKET_CREATE_LOBBY_RES.AddErrorCode(builder, error_code);
    return PACKET_CREATE_LOBBY_RES.EndPACKET_CREATE_LOBBY_RES(builder);
  }

  public static void StartPACKET_CREATE_LOBBY_RES(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddErrorCode(FlatBufferBuilder builder, PacketDefine.ErrorCode errorCode) { builder.AddShort(0, (short)errorCode, 0); }
  public static void AddRoomId(FlatBufferBuilder builder, short roomId) { builder.AddShort(1, roomId, 0); }
  public static void AddEnterKey(FlatBufferBuilder builder, StringOffset enterKeyOffset) { builder.AddOffset(2, enterKeyOffset.Value, 0); }
  public static Offset<PacketDefine.PACKET_CREATE_LOBBY_RES> EndPACKET_CREATE_LOBBY_RES(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<PacketDefine.PACKET_CREATE_LOBBY_RES>(o);
  }
}

public struct PACKET_ENTER_LOBBY_REQ : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_3_3(); }
  public static PACKET_ENTER_LOBBY_REQ GetRootAsPACKET_ENTER_LOBBY_REQ(ByteBuffer _bb) { return GetRootAsPACKET_ENTER_LOBBY_REQ(_bb, new PACKET_ENTER_LOBBY_REQ()); }
  public static PACKET_ENTER_LOBBY_REQ GetRootAsPACKET_ENTER_LOBBY_REQ(ByteBuffer _bb, PACKET_ENTER_LOBBY_REQ obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public PACKET_ENTER_LOBBY_REQ __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public short RoomId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetShort(o + __p.bb_pos) : (short)0; } }
  public string EnterKey { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetEnterKeyBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetEnterKeyBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetEnterKeyArray() { return __p.__vector_as_array<byte>(6); }

  public static Offset<PacketDefine.PACKET_ENTER_LOBBY_REQ> CreatePACKET_ENTER_LOBBY_REQ(FlatBufferBuilder builder,
      short room_id = 0,
      StringOffset enter_keyOffset = default(StringOffset)) {
    builder.StartTable(2);
    PACKET_ENTER_LOBBY_REQ.AddEnterKey(builder, enter_keyOffset);
    PACKET_ENTER_LOBBY_REQ.AddRoomId(builder, room_id);
    return PACKET_ENTER_LOBBY_REQ.EndPACKET_ENTER_LOBBY_REQ(builder);
  }

  public static void StartPACKET_ENTER_LOBBY_REQ(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddRoomId(FlatBufferBuilder builder, short roomId) { builder.AddShort(0, roomId, 0); }
  public static void AddEnterKey(FlatBufferBuilder builder, StringOffset enterKeyOffset) { builder.AddOffset(1, enterKeyOffset.Value, 0); }
  public static Offset<PacketDefine.PACKET_ENTER_LOBBY_REQ> EndPACKET_ENTER_LOBBY_REQ(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<PacketDefine.PACKET_ENTER_LOBBY_REQ>(o);
  }
}

public struct PACKET_ENTER_LOBBY_RES : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_3_3(); }
  public static PACKET_ENTER_LOBBY_RES GetRootAsPACKET_ENTER_LOBBY_RES(ByteBuffer _bb) { return GetRootAsPACKET_ENTER_LOBBY_RES(_bb, new PACKET_ENTER_LOBBY_RES()); }
  public static PACKET_ENTER_LOBBY_RES GetRootAsPACKET_ENTER_LOBBY_RES(ByteBuffer _bb, PACKET_ENTER_LOBBY_RES obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public PACKET_ENTER_LOBBY_RES __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public PacketDefine.ErrorCode ErrCode { get { int o = __p.__offset(4); return o != 0 ? (PacketDefine.ErrorCode)__p.bb.GetShort(o + __p.bb_pos) : PacketDefine.ErrorCode.SUCCESS; } }
  public short RoomId { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetShort(o + __p.bb_pos) : (short)0; } }

  public static Offset<PacketDefine.PACKET_ENTER_LOBBY_RES> CreatePACKET_ENTER_LOBBY_RES(FlatBufferBuilder builder,
      PacketDefine.ErrorCode err_code = PacketDefine.ErrorCode.SUCCESS,
      short room_id = 0) {
    builder.StartTable(2);
    PACKET_ENTER_LOBBY_RES.AddRoomId(builder, room_id);
    PACKET_ENTER_LOBBY_RES.AddErrCode(builder, err_code);
    return PACKET_ENTER_LOBBY_RES.EndPACKET_ENTER_LOBBY_RES(builder);
  }

  public static void StartPACKET_ENTER_LOBBY_RES(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddErrCode(FlatBufferBuilder builder, PacketDefine.ErrorCode errCode) { builder.AddShort(0, (short)errCode, 0); }
  public static void AddRoomId(FlatBufferBuilder builder, short roomId) { builder.AddShort(1, roomId, 0); }
  public static Offset<PacketDefine.PACKET_ENTER_LOBBY_RES> EndPACKET_ENTER_LOBBY_RES(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<PacketDefine.PACKET_ENTER_LOBBY_RES>(o);
  }
}

public struct PACKET_LEAVE_LOBBY_REQ : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_3_3(); }
  public static PACKET_LEAVE_LOBBY_REQ GetRootAsPACKET_LEAVE_LOBBY_REQ(ByteBuffer _bb) { return GetRootAsPACKET_LEAVE_LOBBY_REQ(_bb, new PACKET_LEAVE_LOBBY_REQ()); }
  public static PACKET_LEAVE_LOBBY_REQ GetRootAsPACKET_LEAVE_LOBBY_REQ(ByteBuffer _bb, PACKET_LEAVE_LOBBY_REQ obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public PACKET_LEAVE_LOBBY_REQ __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void StartPACKET_LEAVE_LOBBY_REQ(FlatBufferBuilder builder) { builder.StartTable(0); }
  public static Offset<PacketDefine.PACKET_LEAVE_LOBBY_REQ> EndPACKET_LEAVE_LOBBY_REQ(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<PacketDefine.PACKET_LEAVE_LOBBY_REQ>(o);
  }
}

public struct PACKET_LEAVE_LOBBY_RES : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_3_3(); }
  public static PACKET_LEAVE_LOBBY_RES GetRootAsPACKET_LEAVE_LOBBY_RES(ByteBuffer _bb) { return GetRootAsPACKET_LEAVE_LOBBY_RES(_bb, new PACKET_LEAVE_LOBBY_RES()); }
  public static PACKET_LEAVE_LOBBY_RES GetRootAsPACKET_LEAVE_LOBBY_RES(ByteBuffer _bb, PACKET_LEAVE_LOBBY_RES obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public PACKET_LEAVE_LOBBY_RES __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public PacketDefine.ErrorCode ErrCode { get { int o = __p.__offset(4); return o != 0 ? (PacketDefine.ErrorCode)__p.bb.GetShort(o + __p.bb_pos) : PacketDefine.ErrorCode.SUCCESS; } }

  public static Offset<PacketDefine.PACKET_LEAVE_LOBBY_RES> CreatePACKET_LEAVE_LOBBY_RES(FlatBufferBuilder builder,
      PacketDefine.ErrorCode err_code = PacketDefine.ErrorCode.SUCCESS) {
    builder.StartTable(1);
    PACKET_LEAVE_LOBBY_RES.AddErrCode(builder, err_code);
    return PACKET_LEAVE_LOBBY_RES.EndPACKET_LEAVE_LOBBY_RES(builder);
  }

  public static void StartPACKET_LEAVE_LOBBY_RES(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddErrCode(FlatBufferBuilder builder, PacketDefine.ErrorCode errCode) { builder.AddShort(0, (short)errCode, 0); }
  public static Offset<PacketDefine.PACKET_LEAVE_LOBBY_RES> EndPACKET_LEAVE_LOBBY_RES(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<PacketDefine.PACKET_LEAVE_LOBBY_RES>(o);
  }
}


}
